config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :outfits, only: [:index, :list, :new, :create, :update, :show, :destroy, :edit]

  resources :outfits, only: [:show] do
    resources :reservations, only: [:create, :index, :update]
  end

  resources :reservations, only: [] do
    member do
      patch '/status', to: 'reservations#status'
    end
  end

  get "/dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/outfit.rb
class Outfit < ApplicationRecord
  belongs_to :user
  has_many :reservations
  has_many_attached :photos

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :outfit
  belongs_to :user

  validates :status, inclusion: { in: %w(pending validated canceled) }

  scope :pendings, -> { where status: 'pending' }
  scope :validated, -> { where status: 'validated' }
  scope :canceled, -> { where status: 'canceled'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations
  has_many :outfits, :dependent => :delete_all

  def full_name
    "#{first_name} #{last_name}"
  end

  def pendings
    self.reservations.where(status: 'pending')
  end

  def validated
    self.reservations.where(status: 'validated')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
    def index
        @query = params[:query]
        if params[:query].present?
            sql_query = "name ILIKE :query
            OR description ILIKE :query"
            @outfits = policy_scope(Outfit).where(sql_query, query: "%#{params[:query]}%")
        else
            @outfits = policy_scope(Outfit).order(created_at: :desc)
        end
    end

    def new
        @outfit = Outfit.new
        authorize(@outfit)
    end

    def show
        @outfit = Outfit.find(params[:id])
        authorize(@outfit)
        @reservation = Reservation.new
    end

  def create
    @outfit = Outfit.new(outfit_params)
    @outfit.user = current_user
    authorize(@outfit)

    if @outfit.save
      redirect_to outfit_path(@outfit)
    else
      render "new"
    end
  end

  def list
    @outfits = Outfit.find(params[:user_id])
  end

  def edit
    @outfit = Outfit.find(params[:id])
    authorize(@outfit)
  end

  def update
    @outfit = Outfit.find(params[:id])
    authorize(@outfit)
    @outfit.update(outfit_params)
    # @outfit.assign_attributes(outfit_params)
    redirect_to outfit_path(@outfit)
  end

  def destroy
    @outfit = Outfit.find(params[id])
    @outfit.destroy
    redirect_to outfit_path
  end

private

  def outfit_params
    params.require(:outfit).permit(:id, :name, :description, :price, :category, :image, :user_id, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @outfits = current_user.outfits
    @my_reservations = current_user.reservations
    @received_reservations = @outfits.map do |outfit|
      outfit.reservations
    end.flatten
    @my_pending_reservations = Reservation.pendings.where(user: current_user)
    @my_validated_reservations = Reservation.validated.where(user: current_user)

    @my_received_pending_reservations = current_user.pendings
    @my_received_validated_reservations = current_user.validated
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
    authorize @reservations
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @outfit = Outfit.find(params[:outfit_id])
    @reservation.outfit_id = @outfit.id
    @reservation.user_id = current_user.id
    authorize @reservation
    if @reservation.save!
      flash[:notice] = "Congratulations, your booking has been successefully registered. Please wait for the owner answer"
      redirect_to dashboard_path
    else
      render "new"
    end
  end

  def update
    @reservation = Reservation.find(params[:edit])
    authorize @reservation
    @reservation.update(reservation_params)
    redirect_to outfit_path(@outfit)
  end

  def status
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.update(status: params[:status])
    redirect_to dashboard_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :user_id, :outfit_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :adress, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PANOPLY</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= render "shared/navbar" %>
    <div class="full-height">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/outfits/edit.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1549923746-9507eec27243?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80)">
  Let's edit your outfit!
</div>
<div class="form-style-5">
  <%= simple_form_for [ @user, @outfit ] do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :category %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Update this outfit", class: "btn btn-primary" %>
  <% end %>
  <%= link_to("Return", outfit_path(@outfit)) %>
</div>

app/views/outfits/index.html.erb
<div class= "container">
  <body cz-shortcut-listen="true" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1585914924626-15adac1e6402?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80);">

  <div class="container mt-3">
    <div class="row">
        <div class="col-12">
          <h1>All our <%= @outfits.count %> outfits.</h1>
        </div>
    </div>

  <div class="container mt-3">
    <div class="row">
      <div class="col-8">
        <%= form_tag outfits_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find an outfit to get your futur job"
          %>
      </div>
      <div class="col-4">
          <div class= "btnsearch">
            <%= submit_tag "Search", class: "btn-search" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <% if @query %>
          <p>You searched for <strong><%= @query %></strong>. We found <%= @outfits.count %> matching outfits out of our <%= Outfit.count %> on our website.</p>
        <% else %>
        <% end %>
      </div>
    </div>
    
    <div class="row">
      <% @outfits.each do |outfit| %>
        <div class="col-4">
          <div class="outfit-card">
            <div class="img-fluid img-thumbnail">
                <%= cl_image_tag(outfit.photos.first.key, crop: :fill) %>
            </div>
            <div class="outfit-card-content">
              <div class="outfit-card-title">
                <div class="name">
                  <h4><%= outfit.name %></h4>
                </div>
                <div class=category>
                  <p class="category"><%= outfit.category %></p>
                </div>            
              </div>
              <div class="flex">
                <div class="flex ml-3">
                  <div class=price>
                    <i class="material-icons mr-2">€ per day:</i> <%= outfit.price %>
                  </div>
                </div>
              </div>
              <div class="outfit-card-actions">
                <%= link_to 'More info', outfit_path(outfit), class: "btn btn-flat-index" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/outfits/list.html.erb
<div class="container mt-3">

  <div class="row">
    <div class="col-12">
      <h1>Your closet</h1>
    </div>
  </div>

<div class="row">
    <% @outfits.each do |outfit| %>
      <div class="col-4">
        <div class="outfit-card">
          <div class="outfit-card-image" style="background-image: url('<%= outfit.image %>')"></div>
          <div class="outfit-card-content">
            <div class="outfit-card-title">
              <h4><%= outfit.name %></h4>
            </div>
            <p><%= outfit.category %></p>
            <div class="flex">
              <div class="flex ml-3">
                <i class="material-icons mr-2">€</i> <%= outfit.price %>
              </div>
            </div>
          </div>
          <div class="outfit-card-actions">
            <%= link_to 'More info', outfit_path(outfit) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/outfits/new.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1549923746-9507eec27243?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80)">
  Let's add your outfit!
</div>
<div class="form-style-5">
  <%= simple_form_for [ @user, @outfit ] do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :category %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Create an outfit", class: "btn btn-primary" %>
  <% end %>
</div>

<div class="container"> 
  <a class="btn btn-flat" href="#">Back to all the outfits</a>
</div>

app/views/outfits/show.html.erb
<div class="card-category-show mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.pinimg.com/originals/21/c1/90/21c190b2cad11c6fe4441c7ec9a9b924.jpg)">
  
  <h1 class="show-title">Category: <%= @outfit.category %></h1>
</div>
<div class="container-fluid show-container">
  <div class="row">
    <div  class="col-6">
      <div class="card-product">
        <%= cl_image_tag(@outfit.photos.first.key, crop: :fill) %>
        <div class="card-product-infos">
          <h2><%= @outfit.name %></h2>
          <p><strong>----------</strong></h4>
          <p>The daily price to rent this outfit is:<strong> <%= @outfit.price %> euro </strong></p>
          <p><strong>Is this outfit perfect for you?</strong></p>
          <p><%= @outfit.description %></p>
        </div>
      </div>
    </div>
    <div  class="col-6">
      <div class="calendar">
        <% if ['validated'].include?(@outfit.reservations.last&.status) %>
          <p>We are sorry, this outfit is already booked!</p>
        <% else %>
          <%= simple_form_for [ @outfit, @reservation ] do |f| %>
            <%= f.input :start_date, html5: true %>
            <%= f.input :end_date, html5: true %>
            <%= f.submit "Book this outfit", class: "btn-flat-calendar" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% if current_user.id == @outfit.user_id %>
    <div class= "btn-flat">
      <%= link_to "Edit this outfit",  edit_outfit_path(@outfit), class: 'link-unstyled' %>
    </div>
  <% end %>
 </div>

app/views/pages/dashboard.html.erb
<div class="container mt-5">

  <div class="row">
    <div class="col-12">
      <h1><%= current_user.full_name %>'s profile</h1>
    </div>
  </div>
</div>

<br>

<div class="container mt-5">
  <div class="card-category-show mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1542060748-10c28b62716f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80)">
    <h2>My outfits</h2>
  </div>
  <br>
  <br>
  <div class=grid>
    <% @outfits.each do |outfit| %>
      <div class="reservation-card d-flex justify-content-between">
        <%= cl_image_tag(outfit.photos.first.key, crop: :fill) %>
        <div class="card-padding relative-position align-content-center flex-wrap">
          <div class="reservation-card-content d-flex align-items-start flex-column">
            <h2><%= outfit.name %></h4>
            </p><%= outfit.category %></p>
            <div class="flex ml-3">
              <div class=price><i class="material-icons mr-2">€</i> <%= outfit.price %></div>
            </div>
          </div>
          <div class="outfit-card-actions-dashboard">
            <p class="btn btn-outline-secondary mt-auto btn-radius"><%= link_to 'Update your outfit', edit_outfit_path(outfit.id) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>
<br>
<br>

<div class="container mt-5">
  <div class="card-category-show mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1541840031508-326b77c9a17e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80)">
    <h2>My reservations</h2>
  </div>
    <br>
    <br>
    <div class=grid>
    <% @my_reservations.each do |reservation| %>
      <div class="reservation-card d-flex justify-content-between">
        <%= cl_image_tag(reservation.outfit.photos.first.key, crop: :fill) %>
        <div class="reservation-card-content">
          <h2>Outfit: <%= reservation.outfit.name %></h2>
          <br>
          <p>Booking Period: <%= reservation.start_date.strftime("%A, %b %d") %> - <%= reservation.end_date.strftime("%A, %b %d") %></p>
          <br>
          <p class="badge badge-success"><%= reservation.status %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>
<br>
<br>




<div class="container mt-5">
  <div class="card-category-show mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1565539433134-f41a89c7346e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80)">
    <h2>Reservations requests</h2>
  </div>
  <br>
  <br>
  <h4>To be answered</h4>
  <br>
  <div class=grid>
    <% @received_reservations.each do |reservation| %>
      <% if reservation.status == "pending" %>
        <div class="reservation-card d-flex justify-content-between">
          <%= cl_image_tag(reservation.outfit.photos.first.key, crop: :fill) %>
          <div class="reservation-card-content d-flex align-items-start flex-column">
            <h2>Outfit: <%= reservation.outfit.name %></h2>
            <p>Booking Period: <%= reservation.start_date.strftime("%A, %b %d") %> - <%= reservation.end_date.strftime("%A, %b %d") %></p>
            <p>Booking Status: <%= reservation.status %></p>
            <div class="reservation-card-actions">
              <%= link_to 'Validate', status_reservation_path(reservation, status: 'validated'), method: :patch %>
              <%= link_to 'Decline', status_reservation_path(reservation, status: 'canceled'), method: :patch %>
            </div>
          </div>
        </div>

      <% end %>
    <% end %>
  </div>
  <br>
  <br>
  <h4>Already validated</h4>
  <br>
  <div class=grid>
    <% @received_reservations.each do |reservation| %>
      <% if reservation.status == "validated" %>
          <div class="reservation-card d-flex justify-content-between">
            <%= cl_image_tag(reservation.outfit.photos.first.key, crop: :fill) %>
            <div class="reservation-card-content d-flex align-items-start flex-column">
              <h2>Outfit: <%= reservation.outfit.name %></h2>
              <br>
              <p>Booking Period: <%= reservation.start_date.strftime("%A, %b %d") %> - <%= reservation.end_date.strftime("%A, %b %d") %></p>
              <br>
              <p class="badge badge-success"><%= reservation.status %></p>
            </div>
          </div>
        <% end %>
    <% end %>
  </div>
  <br>
  <br>
  <br>
</div>

app/views/pages/home.html.erb
<head>
  <meta charset="UTF-8">
  <title>My landing page</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <link rel="stylesheet" href="style.css">
</head>


<body cz-shortcut-listen="true" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1518838439236-2b73ceb4638a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1267&q=80); background-size:cover">

  <!-- Banner section -->
<div class="banner">
  <div class="container">
  <br>
    <h1 class="text-center">Welcome on Panoply!</h1>
    <br>
    <br>
    <h3 class="text-center">The market place that allows you to rent the perfect oufit for your upcoming interview!</h32>
  </div>
</div>

  <!-- "How it works" section -->
<div class="container">
  <div class="center-button">
    <%= link_to "Start now", outfits_path, class:"btn-primary-btn-lg" %>
  </div>
  <div class="hiw">
    <h2 class="text-center">How does it work?</h2>
    <br>
    <div class="cards">
      <div class="card">
        <img src="images/logo.png" alt="">
        <h4>1) Find</h4>
        <p class="paragraph-black">Find the perfect outfit for your appointments.</p>
      </div>
      <div class="card">
        <img src="images/logo.png" alt="">
        <h4>2) Rent</h4>
        <p class="paragraph-black">Rent the outfit for some hours.</p>
      </div>
      <div class="card">
        <img src="images/logo.png" alt="">
        <h4>3) Get a job</h4>
        <p class="paragraph-black">Be hired for the best job ever.</p>
      </div>
    </div>
  </div>
</div>
</body>

app/views/reservations/index.html.erb
<div class="container">
 <h1> Reservations Overview </h1>
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h3> Here are all your reservations: </p>
      <ul class="list-group">
        <% @reservations.each do |reservation| %>
          <li class="list-group-item">
            <%= link_to reservation.name, reservation_path(reservation) %>
          </li>
        <% end %>
      </ul>
      <%= link_to "Add a new Reservation", new_reservation_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="links">
    <a href="#"><i class="fab fa-fw fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-fw fa-github"></i></a>
    <a href="#"><i class="fab fa-fw fa-twitter"></i></a>
    <a href="#"><i class="fab fa-fw fa-instagram"></i></a>
    <%# <p>This website was coded with <i class="fas fa-heart"></i> at Le Wagon.</p> %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "..", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/willzor/image/upload/v1619874029/vtm-noir-blanc_nln63l.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home (All our Outfits)", "../outfits", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My profile", "../dashboard", class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "Rent your outfit", new_outfit_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/willzor/image/upload/v1619873791/avatar_itbsit.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Rent an outfit", "../outfits/new", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item red" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>